# Generated by Django 5.2.4 on 2025-07-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0002_alter_course_course_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='course_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_pic',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
