# Generated by Django 5.2.4 on 2025-07-17 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0003_rename_course_student_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestudent',
            name='student',
            field=models.ForeignKey(db_column='registration_id', on_delete=django.db.models.deletion.CASCADE, related_name='collegestudent', to='aryuapp.student'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='student',
            field=models.ForeignKey(db_column='registration_id', on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker', to='aryuapp.student'),
        ),
        migrations.AlterField(
            model_name='schoolstudent',
            name='student',
            field=models.ForeignKey(db_column='registration_id', on_delete=django.db.models.deletion.CASCADE, related_name='schoolstudent', to='aryuapp.student'),
        ),
    ]
