# Generated by Django 5.2.4 on 2025-07-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0004_alter_collegestudent_student_alter_jobseeker_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='syllabus_outline',
        ),
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
