# Generated by Django 5.2.4 on 2025-07-18 10:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0005_remove_course_syllabus_outline_course_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='aryuapp.trainer'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MaxValueValidator(100000)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='students_assigned',
            field=models.ManyToManyField(blank=True, related_name='assigned_trainers', to='aryuapp.student'),
        ),
    ]
