# Generated by Django 5.2.4 on 2025-07-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0007_alter_course_course_name_alter_course_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
