# Generated by Django 5.2.4 on 2025-07-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0008_course_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
