# Generated by Django 5.2.4 on 2025-07-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0010_alter_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
