# Generated by Django 5.2.4 on 2025-07-22 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0011_coursecategory_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_reviewed', to='aryuapp.trainer'),
        ),
    ]
