# Generated by Django 5.2.4 on 2025-07-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0012_alter_leaverequest_reviewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='installment_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='installment_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
