# Generated by Django 5.2.4 on 2025-07-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0013_alter_invoice_installment_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
