# Generated by Django 5.2.4 on 2025-07-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0014_attendance_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
    ]
