# Generated by Django 5.2.4 on 2025-07-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0015_alter_coursecategory_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
