# Generated by Django 5.2.4 on 2025-07-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0017_remove_course_description_remove_course_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
