# Generated by Django 5.2.4 on 2025-07-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0018_topic_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='course_id',
            new_name='course',
        ),
    ]
