# Generated by Django 5.2.4 on 2025-07-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0020_alter_topic_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerlog',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='StudentLog',
        ),
        migrations.DeleteModel(
            name='TrainerLog',
        ),
    ]
