# Generated by Django 5.2.4 on 2025-07-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0021_remove_trainerlog_trainer_delete_studentlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
