# Generated by Django 5.2.4 on 2025-07-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0022_alter_jobseeker_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='courses_assigned',
            field=models.ManyToManyField(blank=True, null=True, to='aryuapp.course'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='students_assigned',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_trainers', to='aryuapp.student'),
        ),
    ]
