# Generated by Django 5.2.4 on 2025-07-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0023_alter_trainer_courses_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
