# Generated by Django 5.2.4 on 2025-07-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0025_alter_assignment_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegestudent',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='internship',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(auto_now_add=True, default='2025-07-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
