# Generated by Django 5.2.4 on 2025-07-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0026_collegestudent_resume_coursecategory_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_name',
        ),
        migrations.AddField(
            model_name='student',
            name='course_name',
            field=models.ManyToManyField(blank=True, to='aryuapp.course'),
        ),
    ]
