# Generated by Django 5.2.4 on 2025-07-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0027_remove_student_course_name_student_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='courses_assigned',
            field=models.ManyToManyField(blank=True, to='aryuapp.course'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='students_assigned',
            field=models.ManyToManyField(blank=True, related_name='assigned_trainers', to='aryuapp.student'),
        ),
    ]
