# Generated by Django 5.2.4 on 2025-07-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0029_alter_collegestudent_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
    ]
