# Generated by Django 5.2.4 on 2025-07-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0030_remove_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_name',
        ),
    ]
