# Generated by Django 5.2.4 on 2025-07-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0031_remove_student_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_name',
            field=models.ManyToManyField(blank=True, to='aryuapp.course'),
        ),
    ]
