# Generated by Django 5.2.4 on 2025-07-25 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0032_student_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='aryuapp.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classschedule',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
