# Generated by Django 5.2.4 on 2025-07-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0033_attendance_course_classschedule_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegestudent',
            name='year_of_study',
        ),
    ]
