# Generated by Django 5.2.4 on 2025-07-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0034_remove_collegestudent_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegestudent',
            name='year_of_study',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
