# Generated by Django 5.2.4 on 2025-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0035_collegestudent_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='duedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
