# Generated by Django 5.2.4 on 2025-07-29 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0037_alter_invoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='student',
            field=models.OneToOneField(db_column='registration_id', on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker', to='aryuapp.student'),
        ),
    ]
