# Generated by Django 5.2.4 on 2025-07-29 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0038_alter_jobseeker_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestudent',
            name='student',
            field=models.OneToOneField(db_column='registration_id', on_delete=django.db.models.deletion.CASCADE, related_name='collegestudent', to='aryuapp.student'),
        ),
        migrations.AlterField(
            model_name='schoolstudent',
            name='student',
            field=models.OneToOneField(db_column='registration_id', on_delete=django.db.models.deletion.CASCADE, related_name='schoolstudent', to='aryuapp.student'),
        ),
    ]
