# Generated by Django 5.2.4 on 2025-07-29 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0039_alter_collegestudent_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolstudent',
            name='student',
        ),
        migrations.CreateModel(
            name='College_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('year_of_study', models.IntegerField()),
                ('student', models.OneToOneField(db_column='registration_id', on_delete=django.db.models.deletion.CASCADE, related_name='college_student', to='aryuapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='School_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_class', models.CharField(max_length=255)),
                ('student', models.OneToOneField(db_column='registration_id', on_delete=django.db.models.deletion.CASCADE, related_name='school_student', to='aryuapp.student')),
            ],
        ),
        migrations.DeleteModel(
            name='CollegeStudent',
        ),
        migrations.DeleteModel(
            name='SchoolStudent',
        ),
    ]
