# Generated by Django 5.2.4 on 2025-07-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0040_remove_schoolstudent_student_college_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(default=False),
        ),
    ]
