# Generated by Django 5.2.4 on 2025-07-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0041_alter_topic_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='id',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
