# Generated by Django 5.2.4 on 2025-07-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0042_remove_topic_id_topic_topic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
