# Generated by Django 5.2.4 on 2025-07-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0043_alter_topic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
