# Generated by Django 5.2.4 on 2025-07-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0044_topic_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='category_pic',
            field=models.ImageField(blank=True, null=True, upload_to='course_categories/'),
        ),
    ]
