# Generated by Django 5.2.4 on 2025-07-30 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0045_coursecategory_category_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
        migrations.CreateModel(
            name='StudentTopicStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_statuses', to='aryuapp.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_statuses', to='aryuapp.topic')),
            ],
        ),
    ]
