# Generated by Django 5.2.4 on 2025-07-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0046_remove_topic_notes_remove_topic_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissionreply',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
