# Generated by Django 5.2.4 on 2025-08-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0047_assignment_is_archived_submission_is_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='duedate',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='priority',
        ),
    ]
