# Generated by Django 5.2.4 on 2025-08-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0048_remove_assignment_duedate_remove_assignment_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='id',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='schedule_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
