# Generated by Django 5.2.4 on 2025-08-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0049_remove_classschedule_id_classschedule_schedule_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='ass_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
