# Generated by Django 5.2.4 on 2025-08-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0050_remove_assignment_id_assignment_ass_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='ass_id',
            new_name='id',
        ),
    ]
