# Generated by Django 5.2.4 on 2025-08-02 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0051_rename_ass_id_assignment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='end_date',
            new_name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='batch',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='student',
            field=models.ManyToManyField(blank=True, to='aryuapp.student'),
        ),
        migrations.RemoveField(
            model_name='batch',
            name='course',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='trainer',
        ),
        migrations.AlterModelTable(
            name='batch',
            table='batch',
        ),
        migrations.CreateModel(
            name='BatchCourseTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aryuapp.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aryuapp.course')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aryuapp.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ManyToManyField(blank=True, to='aryuapp.course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='trainer',
            field=models.ManyToManyField(blank=True, to='aryuapp.trainer'),
        ),
    ]
