# Generated by Django 5.2.4 on 2025-08-02 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0052_rename_end_date_batch_scheduled_date_remove_batch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aryuapp.batch'),
            preserve_default=False,
        ),
    ]
