# Generated by Django 5.2.4 on 2025-08-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0053_classschedule_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='batch',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
