# Generated by Django 5.2.4 on 2025-08-04 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0054_remove_batch_end_time_remove_batch_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='aryuapp.batch'),
            preserve_default=False,
        ),
    ]
