# Generated by Django 5.2.4 on 2025-08-05 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0055_attendance_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcoursetrainer',
            name='student',
            field=models.ForeignKey(default='AYA0725042', on_delete=django.db.models.deletion.CASCADE, to='aryuapp.student'),
            preserve_default=False,
        ),
    ]
