# Generated by Django 5.2.4 on 2025-08-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0056_batchcoursetrainer_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
