# Generated by Django 5.2.4 on 2025-08-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0057_alter_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='course',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='student',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='trainer',
        ),
    ]
