# Generated by Django 5.2.4 on 2025-08-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0059_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchcoursetrainer',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchcoursetrainer', to='aryuapp.batch'),
        ),
    ]
