# Generated by Django 5.2.4 on 2025-08-07 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0060_alter_batchcoursetrainer_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerattendance',
            name='course',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='aryuapp.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submission/'),
        ),
    ]
