# Generated by Django 5.2.5 on 2025-08-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0063_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
