# Generated by Django 5.2.5 on 2025-08-11 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0065_alter_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='student',
            field=models.OneToOneField(db_column='registration_id', default=43, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='aryuapp.student'),
            preserve_default=False,
        ),
    ]
