# Generated by Django 5.2.5 on 2025-08-11 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0066_employee_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='is_online_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='UserGoogleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.TextField(default='https://oauth2.googleapis.com/token')),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('scopes', models.JSONField(default=list)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
