# Generated by Django 5.2.5 on 2025-08-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0067_classschedule_is_online_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerattendance',
            name='sub_topic',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
