# Generated by Django 5.2.5 on 2025-08-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0068_alter_trainerattendance_sub_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerattendance',
            name='topic',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
