# Generated by Django 5.2.5 on 2025-08-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0069_alter_trainerattendance_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='classs_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
