# Generated by Django 5.2.5 on 2025-08-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0070_classschedule_classs_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='classs_link',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
