# Generated by Django 5.2.5 on 2025-08-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0071_alter_classschedule_classs_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classschedule',
            old_name='classs_link',
            new_name='class_link',
        ),
    ]
