# Generated by Django 5.2.5 on 2025-08-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0072_rename_classs_link_classschedule_class_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
