# Generated by Django 5.2.5 on 2025-08-13 08:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0073_batch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('company_contact', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('company_website', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('bank_account_no', models.CharField(max_length=100)),
                ('bank_ifsc', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('gst_detail', models.CharField(max_length=100)),
                ('declaration', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recording', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='aryuapp.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='aryuapp.topic')),
            ],
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
        migrations.DeleteModel(
            name='TermsAndConditions',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='installment_enabled',
            new_name='is_archived',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='amount_due',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fee_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='installment_due',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='installment_paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='installment_plan',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='student',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_payable',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_in_words',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(default=1, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoice/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='per',
            field=models.CharField(default='Nos', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='registration_id',
            field=models.ForeignKey(default="AYA0725043", on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='aryuapp.student'),
            preserve_default=False,
        ),
    ]
