# Generated by Django 5.2.5 on 2025-08-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0074_cms_companydetails_recordings_delete_privacypolicy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_no',
            new_name='invoice_number',
        ),
    ]
