# Generated by Django 5.2.5 on 2025-08-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0075_rename_invoice_no_invoice_invoice_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='registration_id',
            new_name='student',
        ),
    ]
