# Generated by Django 5.2.5 on 2025-08-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0076_rename_registration_id_invoice_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordings',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
