# Generated by Django 5.2.5 on 2025-08-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0078_companydetails_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cms',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cms',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
