# Generated by Django 5.2.5 on 2025-08-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0079_alter_cms_description_alter_cms_link_alter_cms_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
