# Generated by Django 5.2.5 on 2025-08-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0080_cms_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content_pic',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
