# Generated by Django 5.2.5 on 2025-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0081_announcement_content_pic_announcement_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='background_pic',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
