# Generated by Django 5.2.5 on 2025-08-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0082_announcement_background_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
