# Generated by Django 5.2.5 on 2025-08-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0083_alter_announcement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordings',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
