# Generated by Django 5.2.5 on 2025-08-14 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0085_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='aryuapp.employer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
