# Generated by Django 5.2.5 on 2025-08-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0086_employee_employer_employer_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='id',
        ),
        migrations.AddField(
            model_name='employer',
            name='employer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
