# Generated by Django 5.2.5 on 2025-08-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0087_remove_employer_id_employer_employer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='name',
        ),
    ]
