# Generated by Django 5.2.5 on 2025-08-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0090_employee_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employer',
        ),
    ]
