# Generated by Django 5.2.5 on 2025-08-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0092_studenttopicstatus_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttopicstatus',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
