# Generated by Django 5.2.5 on 2025-08-18 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0093_alter_studenttopicstatus_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='employer_id',
            new_name='company_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='manager_password',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='manager_username',
        ),
        migrations.AddField(
            model_name='employee',
            name='company_id',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='aryuapp.employer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='employer',
            table='client_company_details',
        ),
        migrations.CreateModel(
            name='SubAdmin',
            fields=[
                ('employer_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('designation', models.CharField(blank=True, default='sub_admin', max_length=50, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_admins', to='aryuapp.employer')),
            ],
            options={
                'db_table': 'sub_admins',
            },
        ),
    ]
