# Generated by Django 5.2.5 on 2025-08-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0094_rename_employer_id_employer_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadmin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
