# Generated by Django 5.2.5 on 2025-08-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0095_subadmin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadmin',
            name='phone_no',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
