# Generated by Django 5.2.5 on 2025-08-19 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0096_subadmin_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerattendance',
            name='batch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_attendance', to='aryuapp.batch'),
            preserve_default=False,
        ),
    ]
