# Generated by Django 5.2.5 on 2025-08-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0098_employer_status_student_status_subadmin_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
