# Generated by Django 5.2.5 on 2025-08-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0099_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='is_archived',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
