# Generated by Django 5.2.5 on 2025-08-19 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0100_alter_classschedule_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='aryuapp.employer')),
                ('student', models.OneToOneField(db_column='registration_id', on_delete=django.db.models.deletion.CASCADE, related_name='group', to='aryuapp.student')),
            ],
        ),
    ]
