# Generated by Django 5.2.5 on 2025-08-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0103_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='new_data',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='old_data',
        ),
    ]
