# Generated by Django 5.2.5 on 2025-08-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0104_remove_useractivitylog_new_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordings',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 10:28:00'),
            preserve_default=False,
        ),
    ]
