# Generated by Django 5.2.5 on 2025-08-20 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0105_recordings_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
        migrations.AddField(
            model_name='college_student',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_college', to='aryuapp.group'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company_name',
            field=models.CharField(default='Aryu Academy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_employees', to='aryuapp.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='Aryu Academy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='school_student',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_school', to='aryuapp.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
