# Generated by Django 5.2.5 on 2025-08-20 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0106_remove_employee_company_id_remove_group_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college_student',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='school_student',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='group_id',
        ),
        migrations.AddField(
            model_name='college_student',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_college', to='aryuapp.employer'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_employees', to='aryuapp.employer'),
        ),
        migrations.AddField(
            model_name='school_student',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_school', to='aryuapp.employer'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
