# Generated by Django 5.2.5 on 2025-08-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0107_remove_college_student_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
