# Generated by Django 5.2.5 on 2025-08-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0108_alter_cms_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.BooleanField(),
        ),
    ]
