# Generated by Django 5.2.5 on 2025-08-21 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0110_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sub_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aryuapp.subadmin'),
        ),
    ]
