# Generated by Django 5.2.5 on 2025-08-22 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0111_notification_sub_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_jobseeker', to='aryuapp.employer'),
        ),
    ]
