# Generated by Django 5.2.5 on 2025-08-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0112_jobseeker_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
