# Generated by Django 5.2.5 on 2025-08-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0113_alter_employee_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergooglecredentials',
            name='user',
        ),
        migrations.AddField(
            model_name='usergooglecredentials',
            name='trainer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='aryuapp.trainer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
