# Generated by Django 5.2.5 on 2025-08-25 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0114_remove_usergooglecredentials_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerattendance',
            name='sub_topic',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainerattendance',
            name='topic',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aryuapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('option_a', models.TextField(blank=True, null=True)),
                ('option_b', models.TextField(blank=True, null=True)),
                ('option_c', models.TextField(blank=True, null=True)),
                ('option_d', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('marks', models.PositiveBigIntegerField(blank=True, null=True)),
                ('test_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='aryuapp.test')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_option', models.CharField()),
                ('is_correct', models.BooleanField(default=False)),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='aryuapp.student')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_test_answers', to='aryuapp.test')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='aryuapp.testquestions')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=20)),
                ('time_taken', models.DurationField()),
                ('total_marks', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='aryuapp.student')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='aryuapp.test')),
            ],
        ),
    ]
