# Generated by Django 5.2.5 on 2025-08-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0115_alter_trainerattendance_sub_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testquestions',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
