# Generated by Django 5.2.5 on 2025-08-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0116_test_is_archived_testquestions_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswers',
            name='selected_option',
            field=models.TextField(),
        ),
    ]
