# Generated by Django 5.2.5 on 2025-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0117_alter_studentanswers_selected_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
