# Generated by Django 5.2.5 on 2025-08-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0118_alter_test_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestions',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='testquestions',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='testquestions',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='testquestions',
            name='option_d',
        ),
        migrations.AddField(
            model_name='studentanswers',
            name='written_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testquestions',
            name='options',
            field=models.JSONField(blank=True, help_text='MCQ options from frontend', null=True),
        ),
        migrations.AddField(
            model_name='testquestions',
            name='type',
            field=models.CharField(default='mcq', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentanswers',
            name='selected_option',
            field=models.TextField(blank=True, null=True),
        ),
    ]
