# Generated by Django 5.2.5 on 2025-08-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0119_remove_testquestions_option_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
