# Generated by Django 5.2.5 on 2025-09-03 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0122_userpresence_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='duration',
        ),
        migrations.AddField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('recurring_id', models.AutoField(primary_key=True, serialize=False)),
                ('recurrence_type', models.CharField(blank=True, max_length=20, null=True)),
                ('days_of_week', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_online_class', models.BooleanField(default=False)),
                ('class_link', models.TextField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(default='IN', max_length=5)),
                ('subdiv', models.CharField(blank=True, max_length=10, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aryuapp.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aryuapp.course')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aryuapp.trainer')),
            ],
        ),
    ]
