# Generated by Django 5.2.5 on 2025-09-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0123_remove_batch_duration_batch_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(default='all', max_length=20),
        ),
    ]
