# Generated by Django 5.2.5 on 2025-09-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0124_announcement_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
