# Generated by Django 5.2.5 on 2025-09-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0125_attendance_marked_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
