# Generated by Django 5.2.5 on 2025-09-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0126_alter_testresult_percentage_alter_testresult_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='total_marks',
        ),
    ]
