# Generated by Django 5.2.5 on 2025-09-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0127_remove_testresult_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='submitted_at',
        ),
    ]
