# Generated by Django 5.2.5 on 2025-09-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0128_remove_testresult_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringschedule',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
