# Generated by Django 5.2.5 on 2025-09-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0129_recurringschedule_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='created_by',
            new_name='create_by',
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classschedule',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cms',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetails',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recordings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordings',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studenttopicstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenttopicstatus',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subadmin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subadmin',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testquestions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testquestions',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='crreated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 12:40:52.720366+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='contact_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
