# Generated by Django 5.2.5 on 2025-09-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0130_rename_created_by_topic_create_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='crreated_by',
            new_name='created_by',
        ),
    ]
