# Generated by Django 5.2.5 on 2025-09-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0133_clientcompany_created_by_clientcompany_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswers',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
