# Generated by Django 5.2.5 on 2025-09-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0135_alter_studentanswers_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswers',
            name='is_correct',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
