# Generated by Django 5.2.5 on 2025-09-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0137_alter_studentanswers_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswers',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
