# Generated by Django 5.2.5 on 2025-09-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0138_alter_studentanswers_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='password',
            field=models.CharField(default='ak', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
