# Generated by Django 5.2.5 on 2025-09-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0140_batch_notes_course_notes_coursecategory_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='chat/'),
        ),
    ]
