# Generated by Django 5.2.5 on 2025-09-10 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0142_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='evaluated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_results', to='aryuapp.trainer'),
        ),
    ]
