# Generated by Django 5.2.5 on 2025-09-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0143_testresult_evaluated_at_testresult_evaluated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chat/audio/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='chat/uploades/'),
        ),
    ]
