# Generated by Django 5.2.5 on 2025-09-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0144_message_audio_file_alter_message_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswers',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28 10:05:00.61731+00'),
            preserve_default=False,
        ),
    ]
