# Generated by Django 5.2.5 on 2025-09-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0146_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswers',
            name='correct_answer_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswers',
            name='options_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswers',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
