# Generated by Django 5.2.5 on 2025-09-12 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0147_studentanswers_correct_answer_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='aryuapp.student'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='aryuapp.student'),
        ),
        migrations.AlterField(
            model_name='college_student',
            name='student',
            field=models.OneToOneField(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='college_student', to='aryuapp.student'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='student',
            field=models.OneToOneField(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='aryuapp.student'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='student',
            field=models.OneToOneField(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker', to='aryuapp.student'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='aryuapp.student'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='school_student',
            name='student',
            field=models.OneToOneField(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='school_student', to='aryuapp.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userpresence',
            name='user_type',
            field=models.CharField(max_length=20),
        ),
    ]
