# Generated by Django 5.2.5 on 2025-09-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ('aryuapp', '0148_student_student_id_alter_attendance_student_and_more'),
    ]
    
    operations = [
    
        migrations.RunSQL(
            sql="""
            ALTER TABLE aryuapp_student DROP CONSTRAINT IF EXISTS aryuapp_student_pkey;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 2: Ensure student_id is unique
        migrations.RunSQL(
            sql="""
            ALTER TABLE aryuapp_student
            ADD CONSTRAINT student_id_unique UNIQUE (student_id);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 3: Set student_id as primary key
        migrations.RunSQL(
            sql="""
            ALTER TABLE aryuapp_student
            ADD PRIMARY KEY (student_id);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(primary_key=True),
        ),
        # Step 1: Add a temporary column to hold real student_id values
        migrations.AddField(
            model_name='batchcoursetrainer',
            name='student_id_tmp',
            field=models.IntegerField(null=True),
        ),

        # Step 2: Populate temporary column from existing student_id (which currently holds registration_id)
        migrations.RunSQL(
            sql="""
                UPDATE aryuapp_batchcoursetrainer btc
                SET student_id_tmp = s.student_id
                FROM aryuapp_student s
                WHERE btc.registration_id = s.registration_id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 3: Make sure all rows were updated
        # (Optional check in SQL: SELECT COUNT(*) FROM aryuapp_batchcoursetrainer WHERE student_id_tmp IS NULL;)

        # Step 4: Alter temporary column to be a proper ForeignKey to Student
        migrations.AlterField(
            model_name='batchcoursetrainer',
            name='student_id_tmp',
            field=models.ForeignKey(
                to='aryuapp.Student',
                on_delete=django.db.models.deletion.CASCADE,
                db_column='student_id_tmp',
            ),
        ),

        # Step 5: Remove the old student_id column temporarily if needed
        # If you want to keep it as backup, skip this step

        # Step 6: Rename temporary column to student_id
        migrations.RenameField(
            model_name='batchcoursetrainer',
            old_name='student_id_tmp',
            new_name='student_id',
        ),
    ]