# Generated by Django 5.2.5 on 2025-09-12 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0149_alter_batchcoursetrainer_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchcoursetrainer',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='batchcoursetrainer',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='aryuapp.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
