# Generated by Django 5.2.5 on 2025-09-12 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ('aryuapp', '0150_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        # Step 1: Add temporary column to hold student_id
        migrations.AddField(
            model_name='batchcoursetrainer',
            name='student_id_tmp',
            field=models.IntegerField(null=True),
        ),
        # Step 2: Populate temporary column using registration_id
        migrations.RunSQL(
            sql="""
                UPDATE aryuapp_batchcoursetrainer btc
                SET student_id_tmp = s.student_id
                FROM aryuapp_student s
                WHERE btc.registration_id = s.registration_id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 3: Convert the temporary column to a ForeignKey
        migrations.AlterField(
            model_name='batchcoursetrainer',
            name='student_id_tmp',
            field=models.ForeignKey(
                to='aryuapp.Student',
                on_delete=django.db.models.deletion.CASCADE,
                db_column='student_id_tmp',
            ),
        ),

        # Step 5: Rename the temporary column to student_id
        migrations.RenameField(
            model_name='batchcoursetrainer',
            old_name='student_id_tmp',
            new_name='student_id',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE aryuapp_batchcoursetrainer RENAME COLUMN student_id_tmp TO student_id;',
            reverse_sql='ALTER TABLE aryuapp_batchcoursetrainer RENAME COLUMN student_id TO student_id_tmp;'
        )
    ]