# Generated by Django 5.2.5 on 2025-09-12 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0151_alter_batchcoursetrainer_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchcoursetrainer',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='batchcoursetrainer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aryuapp.student'),
        ),
    ]
