# Generated by Django 5.2.5 on 2025-09-12 09:50

from django.db import migrations, models

def migrate_student_ids(apps, schema_editor):
    """
    Update student_id columns to reference real Student.student_id integer values
    instead of varchar registration_id.
    """
    # Use raw SQL to update all tables
    sql_statements = [
        """
        -- School_Student
        ALTER TABLE aryuapp_school_student ADD COLUMN student_id_tmp integer;
        UPDATE aryuapp_school_student ss
        SET student_id_tmp = s.student_id
        FROM aryuapp_student s
        WHERE ss.student_id::varchar = s.registration_id;
        ALTER TABLE aryuapp_school_student DROP COLUMN student_id;
        ALTER TABLE aryuapp_school_student RENAME COLUMN student_id_tmp TO student_id;
        """,
        """
        -- College_Student
        ALTER TABLE aryuapp_college_student ADD COLUMN student_id_tmp integer;
        UPDATE aryuapp_college_student cs
        SET student_id_tmp = s.student_id
        FROM aryuapp_student s
        WHERE cs.student_id::varchar = s.registration_id;
        ALTER TABLE aryuapp_college_student DROP COLUMN student_id;
        ALTER TABLE aryuapp_college_student RENAME COLUMN student_id_tmp TO student_id;
        """,
        """
        -- JobSeeker
        ALTER TABLE aryuapp_jobseeker ADD COLUMN student_id_tmp integer;
        UPDATE aryuapp_jobseeker js
        SET student_id_tmp = s.student_id
        FROM aryuapp_student s
        WHERE js.student_id::varchar = s.registration_id;
        ALTER TABLE aryuapp_jobseeker DROP COLUMN student_id;
        ALTER TABLE aryuapp_jobseeker RENAME COLUMN student_id_tmp TO student_id;
        """,
        """
        -- Employee
        ALTER TABLE aryuapp_employee ADD COLUMN student_id_tmp integer;
        UPDATE aryuapp_employee e
        SET student_id_tmp = s.student_id
        FROM aryuapp_student s
        WHERE e.student_id::varchar = s.registration_id;
        ALTER TABLE aryuapp_employee DROP COLUMN student_id;
        ALTER TABLE aryuapp_employee RENAME COLUMN student_id_tmp TO student_id;
        """
    ]

    for sql in sql_statements:
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0159_alter_topic_status_'),
    ]

    operations = [
        migrations.RunPython(migrate_student_ids),
    ]