# Generated by Django 5.2.5 on 2025-09-12 10:11

from django.db import migrations


def migrate_trainer_students_assigned(apps, schema_editor):
    schema_editor.execute("""
        ALTER TABLE aryuapp_trainer_students_assigned ADD COLUMN student_id_tmp integer;

        UPDATE aryuapp_trainer_students_assigned tsa
        SET student_id_tmp = s.student_id
        FROM aryuapp_student s
        WHERE tsa.student_id = s.registration_id;

        ALTER TABLE aryuapp_trainer_students_assigned DROP COLUMN student_id;

        ALTER TABLE aryuapp_trainer_students_assigned RENAME COLUMN student_id_tmp TO student_id;
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0161_alter_invoice_notification_etc'),
    ]

    operations = [
        migrations.RunPython(migrate_trainer_students_assigned),
    ]
