# Generated by Django 5.2.5 on 2025-09-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0163_alter_student_answers'),
    ]

    operations = [
        # Step 1: Add new temp field
        migrations.AddField(
            model_name='studentanswers',
            name='new_student_id',
            field=models.IntegerField(null=True),
        ),

        # Step 2: Populate new field using registration_id → student_id mapping
        migrations.RunSQL(
            sql="""
                UPDATE aryuapp_studentanswers sa
                SET new_student_id = s.student_id
                FROM aryuapp_student s
                WHERE sa.student_id_id = s.registration_id;
            """,
            reverse_sql="""
                -- Optional reverse if needed
            """
        ),

        # Step 3: Remove old ForeignKey field
        migrations.RemoveField(
            model_name='studentanswers',
            name='student_id',
        ),

        # Step 4: Rename new field to student_id and apply ForeignKey
        migrations.RenameField(
            model_name='studentanswers',
            old_name='new_student_id',
            new_name='student_id',
        ),

        migrations.AlterField(
            model_name='studentanswers',
            name='student_id',
            field=models.ForeignKey(
                to='aryuapp.Student',
                on_delete=models.CASCADE,
                null=True,
                blank=True,
                related_name='student_answers'
            ),
        ),
    ]