# Generated by Django 5.2.5 on 2025-09-18 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0164_alter_student_answers_list'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['batch'], name='aryuapp_cla_batch_i_3004b8_idx'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['scheduled_date'], name='aryuapp_cla_schedul_55d952_idx'),
        ),
    ]
