# Generated by Django 5.2.5 on 2025-09-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0166_permission_role_rolepermission_remove_user_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
