# Generated by Django 5.2.5 on 2025-09-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0168_permission_created_at_permission_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28T11:10:49.000Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
