# Generated by Django 5.2.5 on 2025-09-19 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0169_rolepermission_created_at_rolepermission_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='aryuapp.role'),
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'module_permissions',
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='aryuapp.modulepermission'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
