# Generated by Django 5.2.5 on 2025-09-20 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0170_remove_attendance_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-28T11:10:49.000Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
