# Generated by Django 5.2.5 on 2025-09-20 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0171_remove_attendance_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='currency_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='fee_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
