# Generated by Django 5.2.5 on 2025-09-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0172_remove_attendance_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerattendance',
            name='marked_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
