# Generated by Django 5.2.5 on 2025-09-25 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0173_remove_attendance_student_id_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='rolepermission',
        #     name='permission',
        # ),
        # migrations.RemoveField(
        #     model_name='rolepermission',
        #     name='role',
        # ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(db_column='student_id', default=130, on_delete=django.db.models.deletion.CASCADE, to='aryuapp.student'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ModulePermission',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
