# Generated by Django 5.2.5 on 2025-09-25 09:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0174_remove_rolepermission_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=50, unique=True)),
                ('actions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, help_text='List of actions allowed for this module', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'module_permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aryuapp.role'),
        ),
        migrations.AddField(
            model_name='subadmin',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aryuapp.role'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aryuapp.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aryuapp.role'),
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allowed_actions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, help_text='Actions allowed for this role in this module', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('module_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aryuapp.modulepermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='aryuapp.role')),
            ],
            options={
                'db_table': 'role_module_permissions',
                'unique_together': {('role', 'module_permission')},
            },
        ),
    ]
