# Generated by Django 5.2.5 on 2025-09-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0175_modulepermission_role_and_more'),
    ]

    operations = [
        
    ]
