# Generated by Django 5.2.5 on 2025-09-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0176_remove_batchcoursetrainer_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
                ('company_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('company_email', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=100, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('gst_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('declaration', models.TextField(blank=True, max_length=100, null=True)),
                ('deactivation_options', models.JSONField(blank=True, default=list, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.DeleteModel(
            name='CompanyDetails',
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
