# Generated by Django 5.2.5 on 2025-09-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0177_settings_delete_companydetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeactivationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('deactivated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aryuapp.student')),
            ],
        ),
    ]
