# Generated by Django 5.2.5 on 2025-09-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0179_remove_batchcoursetrainer_student_id_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='attendance_options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
