# Generated by Django 5.2.5 on 2025-09-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0180_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestions',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='testquestions',
            name='mcq_correct_option',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='testquestions',
            name='written_answer',
            field=models.TextField(blank=True, help_text='Correct answer for written questions', null=True),
        ),
    ]
