# Generated by Django 5.2.5 on 2025-09-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0181_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='company_logo',
            new_name='general_logo',
        ),
        migrations.AddField(
            model_name='settings',
            name='secondary_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
