# Generated by Django 5.2.5 on 2025-09-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0182_rename_company_logo_settings_general_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='payment_method',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
