# Generated by Django 5.2.5 on 2025-09-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0183_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='attendance_options',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='deactivation_options',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
