# Generated by Django 5.2.5 on 2025-09-30 10:20

import aryuapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0184_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='general_logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/', validators=[aryuapp.models.validate_image_or_svg]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='secondary_logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/', validators=[aryuapp.models.validate_image_or_svg]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/', validators=[aryuapp.models.validate_image_or_svg]),
        ),
    ]
