# Generated by Django 5.2.5 on 2025-09-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0185_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
