# Generated by Django 5.2.5 on 2025-10-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0187_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['trainer_id'], name='aryuapp_tra_trainer_6df6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['employee_id'], name='aryuapp_tra_employe_f8b9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['full_name', 'user_type'], name='aryuapp_tra_full_na_f3eef6_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['created_by', 'created_by_type'], name='aryuapp_tra_created_b3735a_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['status', 'is_archived'], name='aryuapp_tra_status_17b564_idx'),
        ),
    ]
