# Generated by Django 5.2.5 on 2025-10-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0189_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='coursecategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
