# Generated by Django 5.2.5 on 2025-10-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0190_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='student',
            name='course_name',
        ),
    ]
