# Generated by Django 5.2.5 on 2025-10-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0191_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='courses_assigned',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='students_assigned',
        ),
    ]
