# Generated by Django 5.1.7 on 2025-10-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0192_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGoogleCredentials',
        ),
    ]
