# Generated by Django 5.2.5 on 2025-10-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0194_paymentgateway_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='settings',
            name='paypal_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='stripe_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
