# Generated by Django 5.2.5 on 2025-10-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0195_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='paymentgateway',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
