# Generated by Django 5.2.5 on 2025-10-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0196_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='paymentgateway',
            name='created_by_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='gatway_name',
            field=models.CharField(max_length=50),
        ),
    ]
