# Generated by Django 5.2.5 on 2025-10-10 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0197_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='attendance',
            name='schedule_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aryuapp.classschedule'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
