# Generated by Django 5.2.5 on 2025-10-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0198_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermission',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
