# Generated by Django 5.2.5 on 2025-10-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0199_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='trainerattendance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
