# Generated by Django 5.2.5 on 2025-10-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0200_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='mcq_correct_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
