# Generated by Django 5.1.7 on 2025-10-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0202_remove_batchcoursetrainer_student_id_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(max_length=255),
        ),
    ]
