# Generated by Django 5.2.5 on 2025-10-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0204_rename_parent_guardian_occupation_student_parent_guardian_address_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='student',
            name='parent_guardian_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
