# Generated by Django 5.2.5 on 2025-10-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0205_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_guardian_address',
            new_name='parent_guardian_occupation',
        ),

    ]
