# Generated by Django 5.2.5 on 2025-10-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0206_rename_parent_guardian_address_student_parent_guardian_occupation_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='note',
            name='created_by_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
