# Generated by Django 5.1.7 on 2025-10-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0207_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='is_class_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
