# Generated by Django 5.1.7 on 2025-10-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0209_lead_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='lead_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='is_enabled',
        ),
    ]
