# Generated by Django 5.1.7 on 2025-10-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0210_rename_lead_id_lead_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
