# Generated by Django 5.2.5 on 2025-10-23 06:32

import aryuapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0211_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerTravelExpense',
            fields=[
                ('expense_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('travel_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(db_index=True, default='pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_expenses', to='aryuapp.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerTravelExpenseImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=aryuapp.models.trainer_expense_bill_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='aryuapp.trainertravelexpense')),
            ],
        ),
    ]
