# Generated by Django 5.2.5 on 2025-10-23 06:44

import aryuapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0212_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainertravelexpenseimage',
            name='image',
            field=models.FileField(upload_to=aryuapp.models.trainer_expense_bill_path),
        ),
    ]
