# Generated by Django 5.2.5 on 2025-11-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0215_remove_batchcoursetrainer_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested',
            field=models.BooleanField(default=True),
        ),
    ]
