# Generated by Django 5.2.5 on 2025-11-07 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0216_remove_batchcoursetrainer_student_id_lead_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slots', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_batches', to='aryuapp.course')),
                ('students', models.ManyToManyField(blank=True, related_name='new_batches', to='aryuapp.student')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_batches', to='aryuapp.trainer')),
            ],
        ),
    ]
