# Generated by Django 5.1.7 on 2025-11-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0217_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
