# Generated by Django 5.2.5 on 2025-11-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0218_passwordresetotp_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
