# Generated by Django 5.2.5 on 2025-11-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0219_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbatch',
            name='id',
        ),
        migrations.AddField(
            model_name='newbatch',
            name='batch_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
