# Generated by Django 5.2.5 on 2025-11-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0220_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswers',
            name='marks_snapshot',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
