# Generated by Django 5.2.5 on 2025-11-14 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0221_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='notes',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='new_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='aryuapp.newbatch'),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='new_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='aryuapp.newbatch'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['new_batch'], name='aryuapp_cla_new_bat_247233_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringschedule',
            index=models.Index(fields=['new_batch'], name='aryuapp_rec_new_bat_9fb1f5_idx'),
        ),
    ]
