# Generated by Django 5.2.5 on 2025-11-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0222_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbatch',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
