# Generated by Django 5.2.5 on 2025-11-15 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0223_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringschedule',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aryuapp.batch'),
        ),
    ]
