# Generated by Django 5.2.5 on 2025-11-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0224_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='aryuapp.batch'),
        ),
    ]
