# Generated by Django 5.1.7 on 2025-11-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0225_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['trainer'], name='aryuapp_cla_trainer_8664bb_idx'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['course'], name='aryuapp_cla_course__101ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['created_by'], name='aryuapp_cla_created_6f9b50_idx'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['created_by_type'], name='aryuapp_cla_created_7f40da_idx'),
        ),
    ]
