# Generated by Django 5.2.5 on 2025-11-20 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0226_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerattendance',
            name='schedule_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aryuapp.classschedule'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aryuapp.batch'),
        ),
        migrations.AlterField(
            model_name='trainerattendance',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aryuapp.batch'),
        ),
    ]
