# Generated by Django 5.2.5 on 2025-11-20 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0227_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='new_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='aryuapp.newbatch'),
        ),
        migrations.AddField(
            model_name='trainerattendance',
            name='new_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_attendance', to='aryuapp.newbatch'),
        ),
    ]
