# Generated by Django 5.2.5 on 2025-11-21 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0228_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('months', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_plans', to='aryuapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEMIInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('emi_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='aryuapp.paymentemi')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aryuapp.paymenttransaction')),
            ],
        ),
    ]
