# Generated by Django 5.2.7 on 2025-12-02 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0230_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentemi',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emi_plans', to='aryuapp.course'),
        ),
        migrations.AddField(
            model_name='paymentemiinstallment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aryuapp.course'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_transactions', to='aryuapp.course'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='total_after_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
