# Generated by Django 5.2.7 on 2025-12-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryuapp', '0231_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentticket',
            name='priority',
            field=models.CharField(default='low', max_length=10),
        ),

    ]
