# Generated by Django 5.2.7 on 2025-11-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizroom',
            name='host',
        ),
    ]
