# Generated by Django 5.2.7 on 2025-12-01 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_quiz', '0003_host_quizroom_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizroom',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_quiz_rooms', to='live_quiz.host'),
        ),
    ]
