from django.urls import path
from .views import *
from django.conf.urls.static import static

urlpatterns = [
   path('settings', SettingsViewSet.as_view({'get': 'list', 'post': 'create', 'patch': 'partial_update', 'put': 'update'})),
   path('pics', SettingsPicsViewSet.as_view({'get': 'list'})),
   path('settings/<int:pk>', SettingsViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update', 'put': 'update', 'delete': 'is_archived'})),
   path('cms', CmsViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('cms/<str:link>', CmsViewSet.as_view({'get': 'retrieve'})),
   path("cms/<int:pk>/", CmsViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update', 'put': 'update'})),
   path('cms/<int:pk>/archive', CmsViewSet.as_view({'patch': 'is_archived'})),
   path('login', Login.as_view(), name='login'),
   path('payment_gateway', PaymentGatewayViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('payment_gateway/<int:pk>', PaymentGatewayViewSet.as_view({'get': 'retrieve', 'patch': 'update', 'put': 'update'})),
   path('payment_transaction', PaymentTransactionViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('payment_transaction/<int:pk>', PaymentTransactionViewSet.as_view({'get': 'retrieve'})),
   path('strip/payment_gateway', StripePaymentViewSet.as_view({'post': 'create_payment'})),
   path('paypal/payment_gateway', PayPalPaymentViewSet.as_view({'post': 'create_payment'})),
   path("razorpay/create", RazorpayPaymentViewSet.as_view({"post": "create"})),
   path("razorpay/verify", RazorpayPaymentViewSet.as_view({"post": "verify_payment"})),
   path('stripe/success/', stripe_success),
   path('stripe/cancel/', stripe_cancel),
   path('roles', RoleViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('roles/<int:pk>', RoleViewSet.as_view({'get': 'retrieve', 'patch': 'update', 'put': 'update'})),
   path('roles/<int:pk>/archive', RoleViewSet.as_view({'patch': 'is_archived'})),
   path('modules&permissions', ModulePermissionViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('modules&permissions/<int:pk>', ModulePermissionViewSet.as_view({'get': 'retrieve', 'patch': 'update', 'put': 'update'})),
   path('modules&permissions/<int:pk>/archive', ModulePermissionViewSet.as_view({'patch':'is_archived'})),
   path('roles&permissions', RoleModulePermissionViewSet.as_view({'get': 'list', 'post': 'create', 'patch': 'update', 'put': 'update'})),
   path('roles&permissions/<int:pk>', RoleModulePermissionViewSet.as_view({'get': 'retrieve', 'patch': 'update', 'put': 'update'})),
   path('users', UserViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('users/<str:id>', UserViewSet.as_view({'get': 'retrieve', 'patch': 'update', 'put': 'update', 'delete': 'destroy'})),
   path('users/<str:id>/archive', UserViewSet.as_view({'patch': 'archive_user'})),
   path('admins',TrainerViewSet.as_view({'get': 'list_admins'})),
   path('ad_employee/<str:employee_id>', TrainerViewSet.as_view({'get': 'admin_profile'})),
   path('jarugandi/', ReportsViewSet.as_view({'get': 'get_reports'})),
   path('jarugandi', ReportsViewSet.as_view({'get': 'list'})),
   path('student_registration', StudentRegistration.as_view({'get': 'list', 'post': 'create'})),
   path('student_list',StudentListAPIView.as_view({'get': 'get'}), name='student_list'),
   path('attendance', AdminLogViewSet.as_view({'get': 'list'})),
   path('attendance/<int:student_id>', AttendanceViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('attendance/<int:student_id>/adumneoie', AttendanceViewSet.as_view({'post': 'admin_mark_attendance'})),
   path('attendance/<int:student_id>/full_logs', AttendanceViewSet.as_view({'get': 'full_logs'})),
   path('attendance/<int:student_id>/status', AttendanceViewSet.as_view({'get': 'attendance_status'})),
   path('student_profile/<str:student_id>', StudentProfileViewSet.as_view({'get': 'retrieve','patch': 'partial_update','put': 'update',})),
   path('student_profile/<str:student_id>/courses', StudentProfileViewSet.as_view({'get': 'get_courses_taken'})),
   path('student_profile/<str:student_id>/courses/<str:course_id>', StudentProfileViewSet.as_view({'get': 'get_courses'})),
   path('student_profile/<str:student_id>/archive', StudentProfileViewSet.as_view({'patch': 'archive_student'})),
   path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
   path('verify-otp/', VerifyOTPView.as_view(), name='verify-otp'),
   path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
   path("resend-otp/", ResendOTPView.as_view(), name="resend-otp"),
   path('student_profile/<str:student_id>/reset_password', StudentProfileViewSet.as_view({'patch': 'reset_password'})),
   path("recordings/<str:student_id>", RecordingsView.as_view({'get': 'list', 'post': 'create'})),
   path("recordings/<str:student_id>/<str:recording_id>", RecordingsView.as_view({'get': 'retrieve', 'patch': 'partial_update', 'put': 'update'})),
   path("recordings/<str:student_id>/<str:recording_id>/archive", RecordingsView.as_view({'patch': 'is_archived'})),
   path('invoice', InvoiceCreateView.as_view({'get': 'list', 'post': 'create'})),
   path('invoice/<str:student_id>', InvoiceDetailView.as_view({'get': 'download_pdf'})),
   path('invoice_list', InvoiceListViewSet.as_view({'get': 'list', 'post': 'create'}), name='invoice_list'),
   path('certificate', CertificateViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('certificates/<str:student_id>', CertificateViewSet.as_view({'get': 'student_certificates'})),
   path('courses', CourseViewSet.as_view({'get': 'list', 'post': 'create', 'put': 'update', 'patch': 'partial_update'})),
   path('courses/<str:course_id>', CourseViewSet.as_view({'get': 'retrieve','put': 'update','patch': 'partial_update','delete': 'destroy'})),
   path('courses/<str:course_id>/batches', CourseViewSet.as_view({'get': 'get_batches'})),
   path('courses/<str:course_id>/archive', CourseViewSet.as_view({'patch': 'archive_course'})),
   path('course_categories', CourseCategoryViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('course_categories/<str:category_id>', CourseCategoryViewSet.as_view({'get': 'retrieve','put': 'update','patch': 'partial_update',})),
   path('course_categories/<str:category_id>/archive', CourseCategoryViewSet.as_view({'patch': 'archive_category'})),
   path('trainers', TrainerViewSet.as_view({'get': 'list','post': 'create',})),
   path('trainers/<str:employee_id>', TrainerViewSet.as_view({'get': 'retrieve','patch': 'partial_update','put': 'update','delete': 'destroy',})),
   path('trainer/<str:employee_id>/courses', TrainerViewSet.as_view({'get': 'get_courses_taken'})),
   path('trainer/<str:employee_id>/batches', TrainerViewSet.as_view({'get': 'get_batches'})),
   path('batches/trainer/<str:trainer_id>', NewBatchViewSet.as_view({'get': 'trainer_batches'})),
   path('batches/student/<str:student_id>', NewBatchViewSet.as_view({'get': 'student_batches'})),
   path('trainer/<str:employee_id>/student_list', TrainerViewSet.as_view({'get': 'student_list'})),
   path('trainer/<str:employee_id>/student_list/<str:student_id>', TrainerViewSet.as_view({'get': 'trainer_student_profile'})),
   path('trainer/<str:employee_id>/courses/<str:course_id>', TrainerViewSet.as_view({'get': 'get_courses'})),
   path('trainer/<str:employee_id>/reset_password', TrainerViewSet.as_view({'patch': 'reset_password'})),
   path('trainers/<str:employee_id>/archive',TrainerViewSet.as_view({'patch': 'archive_trainer'})),
   path('trainer_attendance/<str:employee_id>', TrainerAttendanceViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('trainer_attendance/<str:employee_id>/adumneoie', TrainerAttendanceViewSet.as_view({'post': 'admin_mark_attendance'})),
   path('trainer_attendance/<str:employee_id>/full_logs', TrainerAttendanceViewSet.as_view({'get': 'full_logs'})),
   path('trainer_list', TrainerListAPIView.as_view(), name='trainer_list'),
   path('trainer_expenses/<str:trainer_id>', TrainerTravelExpenseViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('trainer_expenses/<str:trainer_id>/<str:expense_id>', TrainerTravelExpenseViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update',})),
   path('trainer_expenses/<str:trainer_id>/<str:expense_id>/archive', TrainerTravelExpenseViewSet.as_view({'patch': 'is_archived'})),
   path('holidays', PublicHolidaysView.as_view({'get': 'list'}), name='public_holidays'),
   path('trainer_attendance', TrainerAttendanceViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('announcements', AnnouncementViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('announcements/<int:id>', AnnouncementViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'})),
   path('announcements/<int:id>/archive', AnnouncementViewSet.as_view({'patch': 'is_archived'})),
   path('feedback', FeedbackViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('leave_request', LeaveRequestViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('class_schedule', ClassScheduleView.as_view({'get': 'list', 'post': 'create'})),
   path('class_schedule/<str:schedule_id>', ClassScheduleView.as_view({'get': 'retrieve', 'patch': 'update','put':'update'})),
   path('class_schedule/<str:employee_id>/schedules', ClassScheduleView.as_view({'get': 'schedules'})),
   path('class_schedule/<str:schedule_id>/archive', ClassScheduleView.as_view({'patch': 'archive'})),
   path("recurring_schedules", RecurringScheduleView.as_view({"post": "create", "get": "list"}),name="recurring_schedules"),
   path("recurring_schedules/<str:pk>", RecurringScheduleView.as_view({"get": "retrieve", "put": "update", "patch": "partial_update"}),name="recurring_schedule-detail"),
   path('batch', BatchViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('batch/<str:batch_id>', BatchViewSet.as_view({'get': 'list', 'put': 'update', 'patch': 'partial_update'})),
   path('batch/<str:batch_id>/archive', BatchViewSet.as_view({'patch': 'is_archived'})),
   path('batches', NewBatchViewSet.as_view({'get': 'list', 'post': 'create'})),
   path('batches/<str:batch_id>', NewBatchViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'update'})),
   path('batches/<str:batch_id>/archive', NewBatchViewSet.as_view({'patch': 'is_archived'})),
   path('student-trainer-data', TrainerStudentMappingAPI.as_view()),
   path('dashboard', UserDashboardView.as_view(), name='user-dashboard'),
   path('employer', EmployerViewSet.as_view({'get': 'list', 'post': 'create'}), name='employer'),
   path('employer/<int:pk>', EmployerViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'}), name='employer-detail'),
   path('employer/<int:pk>/archive', EmployerViewSet.as_view({'patch': 'is_archived'}), name='is_archived'),
   path('employer/<str:company_id>/student_list', EmployerDashboardViewSet.as_view({'get': 'employees'})),
   path('employer/<str:company_id>/attendance', EmployerDashboardViewSet.as_view({'get': 'attendance'})),
   path('subadmin', SubAdminViewSet.as_view({'get': 'list', 'post': 'create'}), name='subadmin'),
   path('subadmin/<int:pk>', SubAdminViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'}), name='subadmin-detail'),
   path('subadmin/<int:pk>/archive', SubAdminViewSet.as_view({'patch': 'is_archived'}), name='is_archived'),
   path('subadmin/<int:pk>/reset_password', SubAdminViewSet.as_view({'patch': 'reset_password'})),
   path('assignments', AssignmentViewSet.as_view({'get': 'list', 'post': 'create'}), name='assignment-list'),
   path('courses/<str:course_id>/assignments', AssignmentViewSet.as_view({'get': 'list_by_course'}), name='list-by-course'),
   path('assignments/<int:pk>/archive', AssignmentViewSet.as_view({'patch': 'is_archived'}), name='assignment-archive'),
   path('assignments/<int:pk>', AssignmentViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', }), name='assignment-detail'),
   path('submissions', SubmissionViewSet.as_view({'get': 'list', 'post': 'create'}), name='submission-list'),
   path('submissions/<int:pk>', SubmissionViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'}), name='submission-detail'),
   path('submissions/<str:registration_id>/<int:pk>/archive', SubmissionViewSet.as_view({'patch': 'is_archived'}), name='submission-archive'),
   path('submissions/<str:registration_id>', SubmissionViewSet.as_view({'get': 'by_student'}), name='submissions-by-student'),
   path('replies', SubmissionReplyViewSet.as_view({'get': 'list', 'post': 'create'}), name='reply-list'),
   path('replies/<int:pk>/archive', SubmissionReplyViewSet.as_view({'patch': 'is_archived'}), name='reply-archive'),
   path('replies/<int:submission_id>', SubmissionReplyViewSet.as_view({'get': 'list', 'post': 'create'}), name='replies-by-submission'),
   path('courses/<str:course_id>/topic', TopicViewSet.as_view({'get': 'list','post': 'create'}), name='topic-list'),
   path('courses/<str:course_id>/topic/<str:student_id>/status', StudentTopicStatusViewSet.as_view({ 'get': 'list' ,'post': 'create'}), name='topic-status'),
   path('courses/<str:course_id>/topic/<int:pk>', TopicViewSet.as_view({'get': 'retrieve','put': 'update','patch': 'partial_update',}), name='topic-detail'),
   path('courses/<str:course_id>/topic/<int:pk>/archive', TopicViewSet.as_view({'patch': 'destroy'})),
   path('test', TestViewSet.as_view({'get': 'list', 'post': 'create'}), name='test-list'),
   path('test/course/<int:course_id>', TestViewSet.as_view({'get': 'tests_by_course'}), name='tests-by-course'),
   path('test/course/<int:course_id>/<str:student_id>', TestViewSet.as_view({'get': 'test_by_students'}), name='test_by_students'),
   path('test/<int:pk>', TestViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'}), name='test-detail'),
   path('test/<int:test_id>/student/<str:student_id>/answers', TestViewSet.as_view({'get': 'student_test_answers'}), name='test-student-answers'),
   path('test/<int:test_id>/student/<str:student_id>/result', TestViewSet.as_view({'get': 'student_test_result'}), name='test-student-result'),
   path('test/<int:pk>/questions', TestViewSet.as_view({'get': 'test_questions'}), name='test-questions'),
   path('test/<int:pk>/archive', TestViewSet.as_view({'patch': 'is_archived'}), name='test-archive'),
   path('test/questions', TestQuestionViewSet.as_view({'get': 'list', 'post': 'create'}), name='question-list'),
   path('test/questions/<int:pk>', TestQuestionViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'}), name='question-detail'),
   path('test/questions/<int:pk>/archive', TestQuestionViewSet.as_view({'patch': 'is_archived'}), name='question-archive'),
   path('answers', StudentAnswerViewSet.as_view({'get': 'list', 'post': 'create'}), name='answer-list'),
   path('answers/<int:pk>', StudentAnswerViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'}), name='answer-detail'),
   path('results/finalize/<int:test_id>/mark_and_finalize', TestResultViewSet.as_view({'get': 'mark_and_finalize', 'post': 'mark_and_finalize'}), name='result-list'),
   path('results/<int:pk>', TestResultViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'}), name='result-detail'),
   path("notifications", NotificationListView.as_view(), name="notification-list"),
   path("notifications/mark_read", mark_notification_read, name="notification-mark-read"),
   path('admins/chat-logs', AdminChatLogViewSet.as_view({'get': 'admin_chat_logs'}), name='admin-chat-logs'),
   path('chat/allama', ChatRoomViewSet.as_view({'get': 'list', 'post': 'create'}), name='chat-list'),
   path('chat/bibbwdx/<int:pk>', ChatRoomViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'}), name='chat-room-detail'),
   path('chat/rooms/<int:room_id>/euybfvh',MessageViewSet.as_view({'get': 'list', 'post': 'create'}), name='message-list'),
   path('chat/yfhyjyft/<int:pk>', MessageViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'}), name='message-detail'),
   path('chat/gcjkhby/<int:room_id>/ywvdajhb', MessageViewSet.as_view({'post': 'mark_as_read'}), name='message-mark-read'),
   path('chat/rooms/<int:room_id>/uyfvchky', MessageViewSet.as_view({'get': 'unread_messages'}), name='unread-count'),
   path('chating/<str:student_id>/eduthuko', ChatRoomViewSet.as_view({'get': 'student_chat_logs'}), name='chating-by-student'),
   path('alllogs', AdminfullLogViewSet.as_view({'get': 'list'})),
   path("tickets/", StudentTicketViewSet.as_view(), name="tickets"),
   path('leads', LeadViewSet.as_view({'get':'list','post':'create'})),
   path('leads/<int:pk>', LeadViewSet.as_view({'get':'retrieve','put':'update','patch':'partial_update'})),
   path('leads/<int:pk>/archive', LeadViewSet.as_view({'patch':'is_archived'})),
   path('leads/<int:pk>/call', LeadViewSet.as_view({'post':'call'})),
   path('leads/<int:pk>/call-logs', LeadViewSet.as_view({'get':'call_logs'})),
   path('leads/<int:pk>/call/<int:call_id>/notes', LeadViewSet.as_view({'post': 'add_call_notes'})),
   path('twilio/connect_customer', connect_customer, name='connect_customer'),
   

   ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

